#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx start