#!/usr/bin/env bash
# Write a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
sudo touch /var/run/holbertonscript.pid
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"

trap interrup2 SIGINT
trap interrup1 SIGTERM
trap interrup3 SIGQUIT

interrup3()
{
    sudo rm /var/run/holbertonscript.pid
    exit $?
}

interrup2()
{
    echo "Y U no love me?!"
}

interrup1()
{
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit $?
}

while true
do
    echo "To infinity and beyond"
    sleep 2
done
