#!/usr/bin/env bash
# A Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
# Requirement:
# Format: IP HTTP_CODE
# in a list format
# See example
# You must use awk
# You are not allowed to use while, for, until and cut
file_s="apache-access.log"
awk -F ' ' '{ print $1, $9 }' $file_s
