#!/usr/bin/env bash
# Script to display "Best School"10 times then "Hi" after 9th line"
s=10
while [ "$s" -gt 0 ]
do
	echo "Best School"
	if [ "$s" -eq 2 ]
	then
		echo "Hi"
	fi
	s=$((s - 1))
done
s=$s
