#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 
s=1
while [ "$s" -le 20 ]
do
    echo "$s"
    case $s in
        4)
	echo "bad luck from China"
        ;;
        9)
	echo "bad luck from Japan"
        ;;
        17)
	echo "bad luck from Italy"
        ;;
    esac

    s=$((s + 1))
done
s=$s
