#!/usr/bin/env bash
# A Bash script that gives you information about the school file
file_s="school"

if [ -e "$file_s" ]
then

    echo "school file exists"
    if [ -s "$file_s" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "$file_s" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
